# Species configuration for knowledge graph generation
# Each species can have 'sample' and/or 'full' dataset configurations
# Note: output_dir is NOT included here - users specify it via --output-dir flag


hsa:
  sample:
    adapters_config: config/hsa/hsa_adapters_config_sample.yaml
    schema_config: config/hsa/hsa_schema_config.yaml
    dbsnp_rsids: aux_files/hsa/sample_dbsnp_rsids.pkl
    dbsnp_pos: aux_files/hsa/sample_dbsnp_pos.pkl
  full:
    adapters_config: config/hsa/hsa_adapters_config.yaml
    schema_config: config/hsa/hsa_schema_config.yaml
    dbsnp_rsids: /mnt/hdd_1/abdu/dbsnp/dbsnp_rsids.pkl
    dbsnp_pos: /mnt/hdd_1/abdu/dbsnp/dbsnp_rsids.pkl

dmel:
  sample:
    adapters_config: config/dmel/dmel_adapters_config_sample.yaml
    schema_config: config/dmel/dmel_schema_config.yaml
    dbsnp_rsids: aux_files/hsa/sample_dbsnp_rsids.pkl
    dbsnp_pos: aux_files/hsa/sample_dbsnp_pos.pkl
  full:
    adapters_config: config/dmel/dmel_adapters_config.yaml
    schema_config: config/dmel/dmel_schema_config.yaml
    dbsnp_rsids: /mnt/hdd_1/abdu/dbsnp/dbsnp_rsids.pkl
    dbsnp_pos: /mnt/hdd_1/abdu/dbsnp/dbsnp_rsids.pkl

cel:
  full:
    adapters_config: config/cel/cel_adapters_config.yaml
    schema_config: config/cel/cel_schema_config.yaml
    dbsnp_rsids: /mnt/hdd_1/abdu/dbsnp/dbsnp_rsids.pkl
    dbsnp_pos: /mnt/hdd_1/abdu/dbsnp/dbsnp_rsids.pkl

mmo:
  full:
    adapters_config: config/mmo/mmo_adapters_config.yaml
    schema_config: config/mmo/mmo_schema_config.yaml
    dbsnp_rsids: /mnt/hdd_1/abdu/dbsnp/dbsnp_rsids.pkl
    dbsnp_pos: /mnt/hdd_1/abdu/dbsnp/dbsnp_rsids.pkl

rno:
  full:
    adapters_config: config/rno/rno_adapters_config.yaml
    schema_config: config/rno/rno_schema_config.yaml
    dbsnp_rsids: /mnt/hdd_1/abdu/dbsnp/dbsnp_rsids.pkl
    dbsnp_pos: /mnt/hdd_1/abdu/dbsnp/dbsnp_rsids.pkl