# Species configuration for knowledge graph generation
# Each species can have 'sample' and/or 'full' dataset configurations
# Note: output_dir is NOT included here - users specify it via --output-dir flag


dmel_net_act:
  sample:
    adapters_config: config/dmel/net_act_adapters_config.yaml
    schema_config: config/dmel/dmel_schema_config.yaml
    dbsnp_rsids: aux_files/hsa/sample_dbsnp_rsids.pkl
    dbsnp_pos: aux_files/hsa/sample_dbsnp_pos.pkl
  full:
    adapters_config: config/dmel/net_act_adapters_config.yaml
    schema_config: config/dmel/dmel_schema_config.yaml
    dbsnp_rsids: aux_files/hsa/sample_dbsnp_rsids.pkl
    dbsnp_pos: aux_files/hsa/sample_dbsnp_pos.pkl

